In [1]:
import numpy as np

In [2]:
d = 2
n = 3
X = np.random.rand(n,d)

In [3]:
X.shape

(3, 2)

In [4]:
X1 = X[:,np.newaxis,:]
X2 = X[np.newaxis,:,:]

In [5]:
X1.shape

(3, 1, 2)

In [6]:
X2.shape

(1, 3, 2)

In [7]:
X1[0]

array([[0.65752447, 0.21215231]])

In [8]:
X2[0]

array([[0.65752447, 0.21215231],
       [0.50985741, 0.56598564],
       [0.89982623, 0.02260451]])

In [9]:
X1[0]-X2[0]

array([[ 0.        ,  0.        ],
       [ 0.14766706, -0.35383333],
       [-0.24230175,  0.18954779]])

In [16]:
d = 200
n = 10
X = np.random.rand(n,d)

In [17]:
X.shape

(10, 200)

In [18]:
D = X[:,np.newaxis,:]-X[np.newaxis,:,:]

In [19]:
D.shape

(10, 10, 200)

In [20]:
D2 = D**2

In [21]:
D2.shape

(10, 10, 200)

In [22]:
SD = np.sum(D2,axis=-1)

In [23]:
SD.shape

(10, 10)

In [24]:
SortedSD = np.argsort(SD,axis=1)

In [26]:
print(SortedSD+1)

[[ 1 10  6  3  8  7  2  5  4  9]
 [ 2  9  6  4  1  7 10  3  5  8]
 [ 3  1  5  6  9  4  8 10  2  7]
 [ 4  9  2  3  5  6  1 10  7  8]
 [ 5 10  3  9  4  1  7  6  2  8]
 [ 6  1  9  7  3  2 10  4  5  8]
 [ 7  6 10  8  1  2  5  4  9  3]
 [ 8  7  1  3 10  9  5  6  4  2]
 [ 9  2  4  6  3  5 10  8  1  7]
 [10  1  5  7  6  9  3  8  2  4]]


In [27]:
S2 = np.argsort(np.sum((X[:,np.newaxis,:]-X[np.newaxis,:,:])**2,axis=-1),axis=1)

In [28]:
print(S2+1)

[[ 1 10  6  3  8  7  2  5  4  9]
 [ 2  9  6  4  1  7 10  3  5  8]
 [ 3  1  5  6  9  4  8 10  2  7]
 [ 4  9  2  3  5  6  1 10  7  8]
 [ 5 10  3  9  4  1  7  6  2  8]
 [ 6  1  9  7  3  2 10  4  5  8]
 [ 7  6 10  8  1  2  5  4  9  3]
 [ 8  7  1  3 10  9  5  6  4  2]
 [ 9  2  4  6  3  5 10  8  1  7]
 [10  1  5  7  6  9  3  8  2  4]]
